name: Oppdater versjonsnummer

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Øk versjonsnummer
        run: |
          echo "Øker versjonsnummer..."
          # Her oppdaterer du versjonsfilen

      - name: Commit og push endringer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Oppdatert versjon automatisk til"
          git push
